from .researcher import Researcher
from .writer import Writer
from .designer import Designer
from .image_gen import ImageGenerator
from .config import POSTS_DIR, API_KEY, PUBLIC_DIR
import os
import markdown
import shutil
import re
from datetime import datetime

# Import utils if needed, but we keep it simple here.

def main():
    print("--- [ AI ADMIN STARTING DAILY ROUTINE ] ---")
    
    # 1. Initialize Agents
    researcher = Researcher()
    writer = Writer()
    designer = Designer()
    image_gen = ImageGenerator()

    # 2. Design Evolution (Thesis-Antithesis-Synthesis)
    designer.evolve_design()

    # 3. Content Creation Loop
    topic_data = researcher.find_topic()
    article_md = writer.write_article(topic_data)
    
    # 4. Visuals
    image_prompt = writer.generate_image_prompt(topic_data['title'])
    svg_content = image_gen.generate_svg(image_prompt)
    
    # 5. Assembly (Build HTML)
    save_article(topic_data, article_md, svg_content)
    
    # 6. Update Index (Simple Append or Rebuild)
    update_index()

    print("--- [ ROUTINE COMPLETE ] ---")

def save_article(topic_data, content_md, svg_content):
    slug = prompt_to_slug(topic_data['title'])
    filename = f"{topic_data['date']}-{slug}.html"
    filepath = os.path.join(POSTS_DIR, filename)
    
    # Convert MD to HTML
    content_html = markdown.markdown(content_md)
    
    # SVG Handling
    svg_html = f'<div class="post-featured-image">{svg_content}</div>' if svg_content else '<div class="post-image-placeholder"></div>'

    full_html = f"""
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{topic_data['title']} | AI Trading</title>
        <base href="../">
        <link rel="stylesheet" href="assets/css/core.css">
        <link rel="stylesheet" href="assets/css/ai_theme.css">
    </head>
    <body class="article-page">
        <header class="site-header">
            <div class="container">
                <a href="index.html" class="logo">AI <span class="highlight">Trading</span></a>
            </div>
        </header>
        
        <main class="container post-container">
            <article>
                {svg_html}
                <br>
                <h1>{topic_data['title']}</h1>
                <div class="post-meta">AI Analysis • {topic_data['date']}</div>
                <hr>
                <div class="post-body">
                    {content_html}
                </div>
            </article>
        </main>
        
        <footer class="site-footer">
            <div class="container"><p>Generated by AI Admin</p></div>
        </footer>
    </body>
    </html>
    """
    
    with open(filepath, "w", encoding='utf-8') as f:
        f.write(full_html)
    print(f"Main: Saved article to {filename}")

def update_index():
    print("Main: Rebuilding Homepage Index...")
    # Read all posts
    posts = []
    for filename in os.listdir(POSTS_DIR):
        if filename.endswith(".html"):
            # Simple parsing of title/date from filename for speed
            # In real app, we'd parse the HTML or use a metadata json
            parts = filename.split('-')
            date = f"{parts[0]}-{parts[1]}-{parts[2]}"
            title_slug = "-".join(parts[3:]).replace(".html", "")
            title = title_slug.replace("-", " ").title()
            
            posts.append({
                "title": title,
                "date": date,
                "url": f"posts/{filename}"
            })
    
    # Sort by date desc
    posts.sort(key=lambda x: x['date'], reverse=True)
    
    # Generate Grid HTML
    grid_html = ""
    for post in posts:
        grid_html += f"""
        <article class="post-card">
            <a href="{post['url']}" style="display:block; text-decoration:none;">
                <div class="post-image-placeholder"></div>
                <div class="post-content">
                    <span class="post-date">{post['date']}</span>
                    <h3>{post['title']}</h3>
                    <p>Click to read AI analysis...</p>
                </div>
            </a>
        </article>
        """
        
    # Inject into Index
    index_path = os.path.join(PUBLIC_DIR, "index.html")
    with open(index_path, "r", encoding='utf-8') as f:
        content = f.read()
    
    # Naive injection marker replacement (or better, BeautifulSoup, but string replace is faster/less deps for now)
    # We will look for <section id="latest" class="posts-grid"> ... </section> and replace inner content
    # Actually, let's just replace the sentinel we put earlier: <!-- Articles will be injected here by AI -->
    # Or cleaner: re-write the specific section.
    
    import re
    new_content = re.sub(
        r'<section id="latest" class="posts-grid">.*?</section>',
        f'<section id="latest" class="posts-grid">{grid_html}</section>',
        content,
        flags=re.DOTALL
    )
    
    with open(index_path, "w", encoding='utf-8') as f:
        f.write(new_content)
    print("Main: Index updated.")

def prompt_to_slug(text):
    return re.sub(r'[^a-zA-Z0-9]', '-', text.lower()).strip('-')

if __name__ == "__main__":
    main()
